Explore Data

In [2]:
import pandas as pd

In [4]:
path = '../DATA/RAW'
fb_file = f'{path}//facebook_ads_raw.csv'
insta_file = f'{path}//instagram_ads_raw.csv'
google_file = f'{path}//google_ads_raw.csv'
yt_file = f'{path}//youtube_ads_raw.csv'

leads_file = f'{path}//leads_raw.csv'
sales_file = f'{path}//Sales_orders_raw.csv'

In [11]:
fb_df = pd.read_csv(fb_file)
fb_df.head()

,date,channel,campaign_id,campaign_name,campaign_objective,ad_group,creative_id,creative_type,target_segment,city,state,device_type,placement,impressions,clicks,video_views,spend_inr,leads,ctr
0,2024-08-21 00:00:00,Facebook,FA-0001,Nova Retail Conversion Campaign - Aug 2024,Conversion,Home & Living - Conversion AdSet,FA-0001-CR1421,Feed Image,Age 55+ | All | Tech Lovers,Chennai,Tamil Nadu,Mobile,Feed,5468.0,91,0,377.79,2.0,0.016642
1,2024-08-21 00:00:00,Facebook,FA-0001,Nova Retail Conversion Campaign - Aug 2024,Conversion,Home & Living - Conversion AdSet,FA-0001-CR9198,Carousel,Age 45-54 | Female | Home Decor,Pune,Maharashtra,Desktop,Feed,2330.0,39,0,194.79,3.0,0.016738
2,2024-08-21 00:00:00,Facebook,FA-0001,Nova Retail Conversion Campaign - Aug 2024,Conversion,Home & Living - Conversion AdSet,FA-0001-CR5823,Feed Image,Age 45-54 | All | Premium Shoppers,Bengaluru,Karnataka,Mobile,Marketplace,7187.0,154,0,610.07,10.0,0.021428
3,2024-08-21 00:00:00,Facebook,FA-0001,Nova Retail Conversion Campaign - Aug 2024,Conversion,Home & Living - Conversion AdSet,FA-0001-CR8224,Feed Image,Age 55+ | Female | Fashion Enthusiasts,Delhi,Delhi,Mobile,Marketplace,8112.0,70,0,705.75,2.0,0.008629
4,2024-08-21 00:00:00,Facebook,FA-0001,Nova Retail Conversion Campaign - Aug 2024,Conversion,Home & Living - Conversion AdSet,FA-0001-CR375,Carousel,Age 55+ | All | Home Decor,Pune,Maharashtra,Mobile,Feed,4734.0,41,0,459.95,3.0,0.008661

In [5]:
yt_df = pd.read_csv(yt_file)
yt_df.head()

,date,channel,campaign_id,campaign_name,campaign_objective,ad_group,creative_id,creative_type,target_segment,city,state,device_type,placement,impressions,clicks,video_views,spend_inr,leads,ctr
0,2024-08-01 00:00:00,YouTube,YO-0001,Fashion New Launch Push,Conversion,Fashion - Conversion AdSet,YO-0001-CR938,Shorts,Age 55+ | All | Premium Shoppers,Kochi,Kerala,Tablet,Shorts,406.0,1,249,66.34,0.0,0.002463
1,2024-08-01 00:00:00,YouTube,YO-0001,Fashion New Launch Push,Conversion,Fashion - Conversion AdSet,YO-0001-CR2574,Skippable In-Stream,Age 45-54 | All | Tech Lovers,Nagpur,Maharashtra,Mobile,Shorts,2057.0,21,1471,179.04,1.0,0.010209
2,2024-08-01 00:00:00,YouTube,YO-0001,Fashion New Launch Push,Conversion,Fashion - Conversion AdSet,YO-0001-CR4523,Skippable In-Stream,Age 18-24 | Female | Tech Lovers,Bengaluru,Karnataka,Tablet,Shorts,1236.0,11,726,178.05,0.0,0.008900
3,2024-08-01 00:00:00,YouTube,YO-0001,Fashion New Launch Push,Conversion,Fashion - Conversion AdSet,YO-0001-CR3755,Bumper,Age 25-34 | Female | Premium Shoppers,Indore,Madhya Pradesh,Tablet,Shorts,388.0,2,177,48.55,0.0,0.005155
4,2024-08-01 00:00:00,YouTube,YO-0001,Fashion New Launch Push,Conversion,Fashion - Conversion AdSet,YO-0001-CR4122,Skippable In-Stream,Age 18-24 | Male | Premium Shoppers,Surat,Gujarat,Mobile,In-Stream,3249.0,20,1506,569.4,0.0,0.006156

In [12]:
insta_df = pd.read_csv(insta_file)
insta_df.head()

,date,channel,campaign_id,campaign_name,campaign_objective,ad_group,creative_id,creative_type,target_segment,city,state,device_type,placement,impressions,clicks,video_views,spend_inr,leads,ctr
0,2024-03-04 00:00:00,Instagram,IN-0001,Nova Retail Home & Living Retargeting,Consideration,Home & Living - Consideration AdSet,IN-0001-CR7287,Feed Image,Age 35-44 | All | Premium Shoppers,Pune,Maharashtra,Desktop,Explore,1862.0,43,0,246.73,1.0,0.023093
1,2024-03-04 00:00:00,Instagram,IN-0001,Nova Retail Home & Living Retargeting,Consideration,Home & Living - Consideration AdSet,IN-0001-CR1965,Feed Image,Age 35-44 | Male | Bargain Hunters,Bengaluru,Karnataka,Mobile,Explore,5864.0,165,0,607.23,4.0,0.028138
2,2024-03-04 00:00:00,Instagram,IN-0001,Nova Retail Home & Living Retargeting,Consideration,Home & Living - Consideration AdSet,IN-0001-CR8009,Reel,Age 35-44 | All | Bargain Hunters,Bengaluru,Karnataka,Desktop,Feed,2889.0,24,0,251.43,1.0,0.008307
3,2024-03-04 00:00:00,instagram,IN-0001,Nova Retail Home & Living Retargeting,Consideration,Home & Living - Consideration AdSet,IN-0001-CR1323,Feed Image,Age 45-54 | Male | Fashion Enthusiasts,Nagpur,Maharashtra,Mobile,Reel,1347.0,28,0,100.63,2.0,0.033803
4,2024-03-04 00:00:00,Instagram,IN-0001,Nova Retail Home & Living Retargeting,Consideration,Home & Living - Consideration AdSet,IN-0001-CR4115,Feed Image,Age 25-34 | Male | Beauty Shoppers,Chennai,Tamil Nadu,Mobile,Reel,4686.0,72,0,467.31,6.0,0.015365

In [5]:
google_df = pd.read_csv(google_file)
google_df.head()

,date,channel,campaign_id,campaign_name,campaign_objective,ad_group,creative_id,creative_type,target_segment,city,state,device_type,placement,impressions,clicks,video_views,spend_inr,leads,ctr
0,2025-11-28 00:00:00,Google Ads,GO-0001,Nova Retail Beauty & Personal Care Conversion ...,Conversion,Beauty & Personal Care - Conversion AdSet,GO-0001-CR9245,Discovery,Age 45-54 | Female | Bargain Hunters,Pune,Maharashtra,Desktop,Discover,1422.0,43,0,153.81,1.0,0.030239
1,2025-11-28 00:00:00,Google Ads,GO-0001,Nova Retail Beauty & Personal Care Conversion ...,Conversion,Beauty & Personal Care - Conversion AdSet,GO-0001-CR3365,Shopping,Age 55+ | Male | Tech Lovers,Delhi,Delhi,Mobile,Search Network,5198.0,196,0,575.4,15.0,0.037707
2,2025-11-28 00:00:00,Google Ads,GO-0001,Nova Retail Beauty & Personal Care Conversion ...,Conversion,Beauty & Personal Care - Conversion AdSet,GO-0001-CR642,Display Banner,Age 35-44 | Male | Bargain Hunters,Surat,Gujarat,Mobile,Shopping Tab,1504.0,51,0,378.92,9.0,0.033910
3,2025-11-28 00:00:00,Google Ads,GO-0001,Nova Retail Beauty & Personal Care Conversion ...,Conversion,Beauty & Personal Care - Conversion AdSet,GO-0001-CR1197,Discovery,Age 55+ | Female | Home Decor,Chandigarh,Punjab,Tablet,Shopping Tab,208.0,3,0,23.25,0.0,0.014423
4,2025-11-28 00:00:00,Google Ads,GO-0001,Nova Retail Beauty & Personal Care Conversion ...,Conversion,Beauty & Personal Care - Conversion AdSet,GO-0001-CR2877,Discovery,Age 25-34 | Male | Bargain Hunters,Kochi,Kerala,Mobile,Discover,1534.0,46,0,229.7,7.0,0.029987

OTHER FILES

In [6]:
leads_df = pd.read_csv(leads_file)
leads_df.head()

,lead_id,date,source_channel,campaign_id,city,device,lead_type,converted_to_sale,conversion_date
0,LEAD-00000001,2025-05-08 00:00:00,Google Ads,GO-0234,Mumbai,Mobile,Wishlist Save,False,NaN
1,LEAD-00000002,2025-09-01 00:00:00,Google Ads,GO-0319,Kochi,Desktop,App Install,False,NaN
2,LEAD-00000003,2024-09-14 00:00:00,Facebook,FA-0346,Kolkata,Mobile,Wishlist Save,False,NaN
3,LEAD-00000004,2025-10-15 00:00:00,Instagram,IN-0030,Delhi,Desktop,Free Trial,False,NaN
4,LEAD-00000005,2024-05-15 00:00:00,Google Ads,GO-0002,Lucknow,Mobile,Free Trial,False,NaN

In [7]:
sales_df = pd.read_csv(sales_file)
sales_df.head()

,order_id,order_date,customer_id,attributed_channel,attributed_campaign_id,product_category,order_value_inr,quantity,discount_pct,payment_method,city,device,is_new_customer,delivery_status
0,ORD-00000001,2025-03-26 00:00:00,CUST-780783,Google Ads,GO-0276,Electronics,14196.41,3.0,0,UPI,Hyderabad,Mobile,False,Delivered
1,ORD-00000002,2024-11-08 00:00:00,CUST-931934,YouTube,YO-0052,Fashion,1266.05,4.0,0,Net Banking,bengaluru,Mobile,False,Delivered
2,ORD-00000003,2024-07-11 00:00:00,CUST-572282,Instagram,IN-0020,Beauty & Personal Care,1180.81,1.0,0,Net Banking,Delhi,Mobile,False,Processing
3,ORD-00000004,26-07-2024,CUST-253527,Google Ads,GO-0156,Beauty & Personal Care,2402.1,2.0,10,Debit Card,Chennai,Mobile,True,Delivered
4,ORD-00000005,2025-01-11 00:00:00,CUST-803570,Instagram,IN-0022,Fashion,4434.2,2.0,10,Net Banking,Bengaluru,Mobile,True,Delivered